CREATE DATABASE CUSTOMER

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT NOT NULL PRIMARY KEY,
	NAME VARCHAR (255) NOT NULL,
	ADDRESS VARCHAR (255) NOT NULL
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID INT NOT NULL PRIMARY KEY,
	NAME VARCHAR (255) NOT NULL,
	PRICE DECIMAL (7,2) CHECK (PRICE>0) NOT NULL
);


CREATE TABLE ORDERS (
    ORDER_ID INT NOT NULL PRIMARY KEY,
	CUSTOMER_ID INT NOT NULL FOREIGN KEY REFERENCES CUSTOMERS (CUSTOMER_ID),
	PRODUCT_ID INT NOT NULL FOREIGN KEY REFERENCES PRODUCTS (PRODUCT_ID),
	QUALITY INT NOT NULL,
	ORDER_DATE DATE NOT NULL
);